import keyMirror from 'keymirror';

export default keyMirror({
  APOLLO_MUTATION_ERROR: null,
  APOLLO_MUTATION_INIT: null,
  APOLLO_MUTATION_RESULT: null,
  RESTART_REGISTRATION: null,
  SET_AUTH_CODE_DIGIT: null,
  SET_REGISTRATION_BUSINESS_NAME: null,
  SET_REGISTRATION_CONSUMER_FIRST_NAME: null,
  SET_REGISTRATION_CONSUMER_LAST_NAME: null,
  SET_REGISTRATION_LINE_TYPE: null,
  SET_REGISTRATION_LISTING_TYPE: null,
  SET_REGISTRATION_PHONE_NUMBER: null,
  SET_REGISTRATION_STEP: null,
  START_REGISTRATION_SESSION: null,
});
