import { Meteor } from 'meteor/meteor';

export const AUTH_CODE_LENGTH = Number(Meteor.settings.AUTH_CODE_LENGTH) || 4;
export const AUTH_CODE_TIMEOUT_SECONDS = Number(Meteor.settings.AUTH_CODE_TIMEOUT_SECONDS) || (60 * 10);
export const DIAL_TIMEOUT_SECONDS = Number(Meteor.settings.DIAL_TIMEOUT_SECONDS) || 20;
export const ENABLE_GRAPHIQL = Meteor.settings.ENABLE_GRAPHIQL === 'true';
export const FEEDBACK_EMAIL_BBC_RECIPIENT = Meteor.settings.FEEDBACK_EMAIL_BBC_RECIPIENT;
export const FEEDBACK_EMAIL_RECIPIENT = Meteor.settings.FEEDBACK_EMAIL_RECIPIENT;
export const GATHER_TIMEOUT_SECONDS = Meteor.settings.GATHER_TIMEOUT_SECONDS || 10;
export const JWT_SECRET = Meteor.settings.JWT_SECRET;
export const KALLEO_COMMUNITY_URI = Meteor.settings.KALLEO_COMMUNITY_URI;
export const KALLEO_MASTER_API_KEY = Meteor.settings.KALLEO_MASTER_API_KEY;
export const MAIL_URL = Meteor.settings.MAIL_URL;
export const MONGO_URI = Meteor.settings.MONGO_URL;
export const NODE_ENV = Meteor.settings.NODE_ENV;
export const PUSH_NOTIFICATION_SOUND_FILENAME = Meteor.settings.PUSH_NOTIFICATION_SOUND_FILENAME;
export const RECENT_CALLS_QUERY_LIMIT = Number(Meteor.settings.RECENT_CALLS_QUERY_LIMIT) || 100;
export const REDIS_URL = Meteor.settings.REDIS_URL;
export const ROLLBAR_ACCESS_TOKEN = Meteor.settings.ROLLBAR_ACCESS_TOKEN;
export const ROOT_URL = NODE_ENV === 'development' ? Meteor.settings.DEV_ROOT_URL : Meteor.settings.ROOT_URL;
export const TEST_SUBSCRIBER_PHONE_NUMBER = Meteor.settings.TEST_SUBSCRIBER_PHONE_NUMBER || '+15555555555';
export const TWILIO_ACCOUNT_SID = Meteor.settings.TWILIO_ACCOUNT_SID;
export const TWILIO_API_KEY = Meteor.settings.TWILIO_API_KEY;
export const TWILIO_API_SECRET = Meteor.settings.TWILIO_API_SECRET;
export const TWILIO_AUTH_TOKEN = Meteor.settings.TWILIO_AUTH_TOKEN;
export const TWILIO_FORWARDING_NUMBERS = Meteor.settings.TWILIO_FORWARDING_NUMBERS ? Meteor.settings.TWILIO_FORWARDING_NUMBERS.split(',') : undefined;
export const TWILIO_PUSH_NOTIFICATION_SID_ANDROID = Meteor.settings.TWILIO_PUSH_NOTIFICATION_SID_ANDROID;
export const TWILIO_PUSH_NOTIFICATION_SID_IOS = Meteor.settings.TWILIO_PUSH_NOTIFICATION_SID_IOS;
export const TWILIO_SMS_PHONE_NUMBER = Meteor.settings.TWILIO_SMS_PHONE_NUMBER;
export const TWILIO_TEST_ACCOUNT_SID = Meteor.settings.TWILIO_TEST_ACCOUNT_SID;
export const TWILIO_TEST_AUTH_TOKEN = Meteor.settings.TWILIO_TEST_AUTH_TOKEN;
export const TWILIO_TEST_CALL_FROM_PHONE_NUMBER = Meteor.settings.TWILIO_TEST_CALL_FROM_PHONE_NUMBER;
export const TWILIO_TEST_CALL_TO_PHONE_NUMBER = Meteor.settings.TWILIO_TEST_CALL_TO_PHONE_NUMBER;
export const TWILIO_TEST_FORWARDING_PHONE_NUMBER = Meteor.settings.TWILIO_TEST_FORWARDING_PHONE_NUMBER;
export const TWILIO_VERIFICATION_PHONE_NUMBER = Meteor.settings.TWILIO_VERIFICATION_PHONE_NUMBER;
export const TWILIO_VOIP_SID_ANDROID = Meteor.settings.TWILIO_VOIP_SID_ANDROID;
export const TWILIO_VOIP_SID_IOS = Meteor.settings.TWILIO_VOIP_SID_IOS;
export const USE_TWILIO_TEST_CREDENTIALS = NODE_ENV !== 'production';
export const VOICEMAIL_MAX_SECONDS = Number(Meteor.settings.VOICEMAIL_MAX_SECONDS) || 90;
export const VERIFICATION_TIMEOUT_MS = Number(Meteor.settings.VERIFICATION_TIMEOUT_MS) || 3000;
